### ISSUE TITLE
Error at the end of the video

### ISSUE THREAD

**Issue by rahulshw** [ThuAbLKA/flutter-vimeo-player#1]
Your package is of great help to me. But, I am seeing the following error at the end of the video. I think it has to do with the end slider value. Any help would be appreciated. 

Error: ```'package:flutter/src/material/slider.dart': Failed assertion: line 132 pos 15: 'value >= min && value <= max': is not true.```

**Comment by KIMDara** [comment]
this pack is awesome . that help me a lot . thank you . but i don't know how to use onEnded callback function. Could you tell me to to add it ?

**Comment by KIMDara** [comment]
<img width="388" alt="Screen Shot 2020-06-05 at 12 17 28 AM" src="https://user-images.githubusercontent.com/42166658/83790163-f22a9f80-a6c1-11ea-9842-522e224a7013.png">

**Comment by ThuAbLKA** [comment]
Hi, So sorry for the late reply. Please get the latest update. I have fixed a number of issues and added some new features as well.
