### ISSUE TITLE
Does the lib support iOS?

### ISSUE THREAD

**Issue by huybuidac** [ThuAbLKA/flutter-vimeo-player#2]
I tried sample project on both simulator on real device, then it doesn't work - iOS: 13.5

So, does the lib support iOS?

**Comment by ThuAbLKA** [comment]
Hi @huybuidac this library does not fully support iOS yet. I'm working on getting the feature out as soon as possible!

**Comment by huybuidac** [comment]
I really look forward to the ios supported version.
Thanks for your effort.
